stages:
  - build_push

build_push:
  stage: build_push
  image:
    name: quay.io/buildah/stable:latest
  before_script:
    - buildah login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - buildah bud --pull -f Containerfile -t "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - buildah tag "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" "${DOCKER_REGISTRY_IMAGE}:latest"
    - buildah push "${DOCKER_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - buildah push "${DOCKER_REGISTRY_IMAGE}:latest"
